<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cetak Semua KTM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    @include('components.styles.ktm-semua-style')
</head>
<body>

<div class="ktm-container">
    <h1 class="text-center mb-4">Daftar Kartu Tanda Mahasiswa</h1>
    
    <!-- Wrapper for all KTM cards -->
    <div class="ktm-card-wrapper">
        @foreach($mahasiswas as $mahasiswa)
        <div class="ktm-card" id="ktm-card-{{ $mahasiswa->id }}">
            <div class="ktm-card-header">
                <h2>KTM Mahasiswa</h2>
            </div>
            
            <div class="ktm-details">
                <p><strong>NIM:</strong> {{ $mahasiswa->nim }}</p>
                <p><strong>Nama:</strong> {{ $mahasiswa->name }}</p>
                <p><strong>Jurusan:</strong> {{ $mahasiswa->jurusan }}</p>
                <p><strong>Fakultas:</strong> {{ $mahasiswa->fakultas }}</p>
                <p><strong>Tanggal Lahir:</strong> {{ \Carbon\Carbon::parse($mahasiswa->tanggal_lahir)->format('d M Y') }}</p>
            </div>

            <div class="ktm-image-container">
                <img src="{{ asset('storage/' . $mahasiswa->image) }}" alt="Foto Mahasiswa" class="ktm-image">
            </div>

            <div class="ktm-footer">
                <p><small>Generated by Your University System</small></p>
            </div>

            <!-- Button to download the card -->
            <button class="download-btn" onclick="downloadKTM({{ $mahasiswa->id }})">Download KTM</button>
        </div>
        @endforeach
    </div>
</div>

@include('components.scripts.ktm-semua-script')


</body>
</html>
